/**
 * This file was copied and re-packaged automatically by
 *     org.xtext.example.delphi.build.GenerateCS2AST
 * from 
 *     ..\..\org.eclipse.qvtd-master\plugins\org.eclipse.qvtd.runtime\src\org\eclipse\qvtd\runtime\evaluation\DefaultInterval.java
 *
 * Do not edit this file. 
 */
/*******************************************************************************
 * Copyright (c) 2016 Willink Transformations and others.
 * All rights reserved.   This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   E.D.Willink - Initial API and implementation
 *******************************************************************************/
package org.xtext.example.delphi.tx;

import org.eclipse.jdt.annotation.NonNull;
import org.xtext.example.delphi.internal.tx.AbstractIntervalInternal;

/**
 * DefaultInterval provides the standard implementation of the scheduling interval manager.
 */
public class DefaultInterval extends AbstractIntervalInternal
{
	public DefaultInterval(@NonNull InvocationManager invocationManager, int intervalIndex) {
		super(invocationManager, intervalIndex);
	}
}
