/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Stmnt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.delphi.delphi.CallStmnt#getDesignator <em>Designator</em>}</li>
 *   <li>{@link org.xtext.example.delphi.delphi.CallStmnt#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.delphi.delphi.DelphiPackage#getCallStmnt()
 * @model
 * @generated
 */
public interface CallStmnt extends simpleStatement
{
  /**
   * Returns the value of the '<em><b>Designator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Designator</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Designator</em>' containment reference.
   * @see #setDesignator(designator)
   * @see org.xtext.example.delphi.delphi.DelphiPackage#getCallStmnt_Designator()
   * @model containment="true"
   * @generated
   */
  designator getDesignator();

  /**
   * Sets the value of the '{@link org.xtext.example.delphi.delphi.CallStmnt#getDesignator <em>Designator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Designator</em>' containment reference.
   * @see #getDesignator()
   * @generated
   */
  void setDesignator(designator value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(exprList)
   * @see org.xtext.example.delphi.delphi.DelphiPackage#getCallStmnt_Args()
   * @model containment="true"
   * @generated
   */
  exprList getArgs();

  /**
   * Sets the value of the '{@link org.xtext.example.delphi.delphi.CallStmnt#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(exprList value);

} // CallStmnt
