/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>conditional Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.delphi.delphi.DelphiPackage#getconditionalStmt()
 * @model
 * @generated
 */
public interface conditionalStmt extends structStmt
{
} // conditionalStmt
