/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>decl Section</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.delphi.delphi.DelphiPackage#getdeclSection()
 * @model
 * @generated
 */
public interface declSection extends EObject
{
} // declSection
