/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>enumerated Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.delphi.delphi.enumeratedType#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.delphi.delphi.DelphiPackage#getenumeratedType()
 * @model
 * @generated
 */
public interface enumeratedType extends ordinalType
{
  /**
	 * Returns the value of the '<em><b>Element</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.delphi.delphi.enumeratedTypeElement}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Element</em>' containment reference list.
	 * @see org.xtext.example.delphi.delphi.DelphiPackage#getenumeratedType_Element()
	 * @model containment="true"
	 * @generated
	 */
  EList<enumeratedTypeElement> getElement();

} // enumeratedType
