/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>method Heading</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.delphi.delphi.methodHeading#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.delphi.delphi.methodHeading#getFormalParams <em>Formal Params</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.delphi.delphi.DelphiPackage#getmethodHeading()
 * @model
 * @generated
 */
public interface methodHeading extends CSTrace
{
  /**
	 * Returns the value of the '<em><b>Id</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Id</em>' containment reference.
	 * @see #setId(ident)
	 * @see org.xtext.example.delphi.delphi.DelphiPackage#getmethodHeading_Id()
	 * @model containment="true"
	 * @generated
	 */
  ident getId();

  /**
	 * Sets the value of the '{@link org.xtext.example.delphi.delphi.methodHeading#getId <em>Id</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Id</em>' containment reference.
	 * @see #getId()
	 * @generated
	 */
  void setId(ident value);

  /**
	 * Returns the value of the '<em><b>Formal Params</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Formal Params</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Formal Params</em>' containment reference.
	 * @see #setFormalParams(formalParameters)
	 * @see org.xtext.example.delphi.delphi.DelphiPackage#getmethodHeading_FormalParams()
	 * @model containment="true"
	 * @generated
	 */
  formalParameters getFormalParams();

  /**
	 * Sets the value of the '{@link org.xtext.example.delphi.delphi.methodHeading#getFormalParams <em>Formal Params</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Formal Params</em>' containment reference.
	 * @see #getFormalParams()
	 * @generated
	 */
  void setFormalParams(formalParameters value);

} // methodHeading
