/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>mul Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.delphi.delphi.mulExp#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.delphi.delphi.mulExp#getMulOp <em>Mul Op</em>}</li>
 *   <li>{@link org.xtext.example.delphi.delphi.mulExp#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.delphi.delphi.DelphiPackage#getmulExp()
 * @model
 * @generated
 */
public interface mulExp extends term
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(term)
   * @see org.xtext.example.delphi.delphi.DelphiPackage#getmulExp_Left()
   * @model containment="true"
   * @generated
   */
  term getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.delphi.delphi.mulExp#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(term value);

  /**
   * Returns the value of the '<em><b>Mul Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mul Op</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mul Op</em>' containment reference.
   * @see #setMulOp(mulOp)
   * @see org.xtext.example.delphi.delphi.DelphiPackage#getmulExp_MulOp()
   * @model containment="true"
   * @generated
   */
  mulOp getMulOp();

  /**
   * Sets the value of the '{@link org.xtext.example.delphi.delphi.mulExp#getMulOp <em>Mul Op</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mul Op</em>' containment reference.
   * @see #getMulOp()
   * @generated
   */
  void setMulOp(mulOp value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(factor)
   * @see org.xtext.example.delphi.delphi.DelphiPackage#getmulExp_Right()
   * @model containment="true"
   * @generated
   */
  factor getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.delphi.delphi.mulExp#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(factor value);

} // mulExp
