/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>property Interface</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.delphi.delphi.propertyInterface#getParamList <em>Param List</em>}</li>
 *   <li>{@link org.xtext.example.delphi.delphi.propertyInterface#getId <em>Id</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.delphi.delphi.DelphiPackage#getpropertyInterface()
 * @model
 * @generated
 */
public interface propertyInterface extends EObject
{
  /**
   * Returns the value of the '<em><b>Param List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param List</em>' containment reference.
   * @see #setParamList(propertyParameterList)
   * @see org.xtext.example.delphi.delphi.DelphiPackage#getpropertyInterface_ParamList()
   * @model containment="true"
   * @generated
   */
  propertyParameterList getParamList();

  /**
   * Sets the value of the '{@link org.xtext.example.delphi.delphi.propertyInterface#getParamList <em>Param List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param List</em>' containment reference.
   * @see #getParamList()
   * @generated
   */
  void setParamList(propertyParameterList value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' containment reference.
   * @see #setId(ident)
   * @see org.xtext.example.delphi.delphi.DelphiPackage#getpropertyInterface_Id()
   * @model containment="true"
   * @generated
   */
  ident getId();

  /**
   * Sets the value of the '{@link org.xtext.example.delphi.delphi.propertyInterface#getId <em>Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' containment reference.
   * @see #getId()
   * @generated
   */
  void setId(ident value);

} // propertyInterface
