/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>qual Id</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.delphi.delphi.qualId#getUnitId <em>Unit Id</em>}</li>
 *   <li>{@link org.xtext.example.delphi.delphi.qualId#getId <em>Id</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.delphi.delphi.DelphiPackage#getqualId()
 * @model
 * @generated
 */
public interface qualId extends CSTrace
{
  /**
	 * Returns the value of the '<em><b>Unit Id</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unit Id</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Unit Id</em>' containment reference.
	 * @see #setUnitId(unitId)
	 * @see org.xtext.example.delphi.delphi.DelphiPackage#getqualId_UnitId()
	 * @model containment="true"
	 * @generated
	 */
  unitId getUnitId();

  /**
	 * Sets the value of the '{@link org.xtext.example.delphi.delphi.qualId#getUnitId <em>Unit Id</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Unit Id</em>' containment reference.
	 * @see #getUnitId()
	 * @generated
	 */
  void setUnitId(unitId value);

  /**
	 * Returns the value of the '<em><b>Id</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Id</em>' containment reference.
	 * @see #setId(ident)
	 * @see org.xtext.example.delphi.delphi.DelphiPackage#getqualId_Id()
	 * @model containment="true"
	 * @generated
	 */
  ident getId();

  /**
	 * Sets the value of the '{@link org.xtext.example.delphi.delphi.qualId#getId <em>Id</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Id</em>' containment reference.
	 * @see #getId()
	 * @generated
	 */
  void setId(ident value);

} // qualId
