/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>real Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.delphi.delphi.DelphiPackage#getrealType()
 * @model
 * @generated
 */
public interface realType extends simpleType
{
} // realType
