/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>simple Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.delphi.delphi.DelphiPackage#getsimpleExpression()
 * @model
 * @generated
 */
public interface simpleExpression extends expression
{
} // simpleExpression
