/*
 * generated by Xtext
 */
package uk.ac.york.cs.asbh.ui.outline

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class ASBHLangOutlineTreeProvider extends uk.ac.york.cs.asbh.ui.outline.CS2ASOutlineTreeProvider {
	
}
