<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cs2asanalysis" nsURI="http://cs2asanalysis" nsPrefix="cs2asana">
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eOperations name="toString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return ToStringSwitch.INSTANCE.doSwitch(this);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return toString().hashCode();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="equals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return toString().equals(object.toString());"/>
      </eAnnotations>
      <eParameters name="object" eType="ecore:EDataType ../../org.eclipse.ocl.examples.pivot/model/Pivot.ecore#//Object"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CS2ASAnalysisNode" abstract="true" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.pivot/model/Pivot.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredElement" eType="ecore:EClass ../../org.eclipse.ocl.examples.pivot/model/Pivot.ecore#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionNode" abstract="true" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfoNode" abstract="true" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationRef" abstract="true" eSuperTypes="#//CS2ASAnalysisNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.pivot/model/Pivot.ecore#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyRef" abstract="true" eSuperTypes="#//CS2ASAnalysisNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.pivot/model/Pivot.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassRef" abstract="true" eSuperTypes="#//CS2ASAnalysisNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" lowerBound="1" eType="ecore:EClass ../../org.eclipse.ocl.examples.pivot/model/Pivot.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorPartPropRef" abstract="true"
      eSuperTypes="#//PropertyRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constructorPart" eType="ecore:EClass ../../org.eclipse.ocl.examples.pivot/model/Pivot.ecore#//ConstructorPart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassInfo" eSuperTypes="#//ClassRef #//InfoNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorExpClassInfo" eSuperTypes="#//ClassInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constructorExp" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.pivot/model/Pivot.ecore#//ConstructorExp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorPartAction" eSuperTypes="#//ConstructorPartPropRef #//ActionNode">
    <eOperations name="toString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return super.toString();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="needsLookup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorPartPropertyInfo" eSuperTypes="#//ExtendedPropertyInfo #//ConstructorPartPropRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedPropertyInfo" eSuperTypes="#//PropertyRef #//InfoNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyClass" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.pivot/model/Pivot.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationAction" eSuperTypes="#//OperationRef #//ActionNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyCallExpInfo" eSuperTypes="#//PropertyRef #//InfoNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyCallExp" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.examples.pivot/model/Pivot.ecore#//PropertyCallExp"/>
  </eClassifiers>
</ecore:EPackage>
