/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.abnf.aBNF;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.abnf.aBNF.attribute#getOPTA <em>OPTA</em>}</li>
 *   <li>{@link org.xtext.example.abnf.aBNF.attribute#getSEM <em>SEM</em>}</li>
 *   <li>{@link org.xtext.example.abnf.aBNF.attribute#getNAME <em>NAME</em>}</li>
 *   <li>{@link org.xtext.example.abnf.aBNF.attribute#getTYPE <em>TYPE</em>}</li>
 *   <li>{@link org.xtext.example.abnf.aBNF.attribute#getMULTA <em>MULTA</em>}</li>
 *   <li>{@link org.xtext.example.abnf.aBNF.attribute#getMULTB <em>MULTB</em>}</li>
 *   <li>{@link org.xtext.example.abnf.aBNF.attribute#getOPTB <em>OPTB</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.abnf.aBNF.ABNFPackage#getattribute()
 * @model
 * @generated
 */
public interface attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>OPTA</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>OPTA</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>OPTA</em>' attribute.
   * @see #setOPTA(String)
   * @see org.xtext.example.abnf.aBNF.ABNFPackage#getattribute_OPTA()
   * @model
   * @generated
   */
  String getOPTA();

  /**
   * Sets the value of the '{@link org.xtext.example.abnf.aBNF.attribute#getOPTA <em>OPTA</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>OPTA</em>' attribute.
   * @see #getOPTA()
   * @generated
   */
  void setOPTA(String value);

  /**
   * Returns the value of the '<em><b>SEM</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>SEM</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>SEM</em>' attribute.
   * @see #setSEM(String)
   * @see org.xtext.example.abnf.aBNF.ABNFPackage#getattribute_SEM()
   * @model
   * @generated
   */
  String getSEM();

  /**
   * Sets the value of the '{@link org.xtext.example.abnf.aBNF.attribute#getSEM <em>SEM</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SEM</em>' attribute.
   * @see #getSEM()
   * @generated
   */
  void setSEM(String value);

  /**
   * Returns the value of the '<em><b>NAME</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>NAME</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>NAME</em>' attribute.
   * @see #setNAME(String)
   * @see org.xtext.example.abnf.aBNF.ABNFPackage#getattribute_NAME()
   * @model
   * @generated
   */
  String getNAME();

  /**
   * Sets the value of the '{@link org.xtext.example.abnf.aBNF.attribute#getNAME <em>NAME</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>NAME</em>' attribute.
   * @see #getNAME()
   * @generated
   */
  void setNAME(String value);

  /**
   * Returns the value of the '<em><b>TYPE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>TYPE</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>TYPE</em>' attribute.
   * @see #setTYPE(String)
   * @see org.xtext.example.abnf.aBNF.ABNFPackage#getattribute_TYPE()
   * @model
   * @generated
   */
  String getTYPE();

  /**
   * Sets the value of the '{@link org.xtext.example.abnf.aBNF.attribute#getTYPE <em>TYPE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>TYPE</em>' attribute.
   * @see #getTYPE()
   * @generated
   */
  void setTYPE(String value);

  /**
   * Returns the value of the '<em><b>MULTA</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>MULTA</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>MULTA</em>' attribute.
   * @see #setMULTA(String)
   * @see org.xtext.example.abnf.aBNF.ABNFPackage#getattribute_MULTA()
   * @model
   * @generated
   */
  String getMULTA();

  /**
   * Sets the value of the '{@link org.xtext.example.abnf.aBNF.attribute#getMULTA <em>MULTA</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MULTA</em>' attribute.
   * @see #getMULTA()
   * @generated
   */
  void setMULTA(String value);

  /**
   * Returns the value of the '<em><b>MULTB</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>MULTB</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>MULTB</em>' attribute.
   * @see #setMULTB(String)
   * @see org.xtext.example.abnf.aBNF.ABNFPackage#getattribute_MULTB()
   * @model
   * @generated
   */
  String getMULTB();

  /**
   * Sets the value of the '{@link org.xtext.example.abnf.aBNF.attribute#getMULTB <em>MULTB</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MULTB</em>' attribute.
   * @see #getMULTB()
   * @generated
   */
  void setMULTB(String value);

  /**
   * Returns the value of the '<em><b>OPTB</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>OPTB</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>OPTB</em>' attribute.
   * @see #setOPTB(String)
   * @see org.xtext.example.abnf.aBNF.ABNFPackage#getattribute_OPTB()
   * @model
   * @generated
   */
  String getOPTB();

  /**
   * Sets the value of the '{@link org.xtext.example.abnf.aBNF.attribute#getOPTB <em>OPTB</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>OPTB</em>' attribute.
   * @see #getOPTB()
   * @generated
   */
  void setOPTB(String value);

} // attribute
