/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.delphi.delphi.DelphiPackage;
import org.xtext.example.delphi.delphi.constructorHeading;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>constructor Heading</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class constructorHeadingImpl extends methodHeadingImpl implements constructorHeading
{
  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected constructorHeadingImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return DelphiPackage.Literals.CONSTRUCTOR_HEADING;
	}

} //constructorHeadingImpl
