/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.delphi.delphi.DelphiPackage;
import org.xtext.example.delphi.delphi.library;
import org.xtext.example.delphi.delphi.programBlock;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>library</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.delphi.delphi.impl.libraryImpl#getPBlock <em>PBlock</em>}</li>
 * </ul>
 *
 * @generated
 */
public class libraryImpl extends fileImpl implements library
{
  /**
	 * The cached value of the '{@link #getPBlock() <em>PBlock</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getPBlock()
	 * @generated
	 * @ordered
	 */
  protected programBlock pBlock;

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected libraryImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return DelphiPackage.Literals.LIBRARY;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public programBlock getPBlock()
  {
		return pBlock;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public NotificationChain basicSetPBlock(programBlock newPBlock, NotificationChain msgs)
  {
		programBlock oldPBlock = pBlock;
		pBlock = newPBlock;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DelphiPackage.LIBRARY__PBLOCK, oldPBlock, newPBlock);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public void setPBlock(programBlock newPBlock)
  {
		if (newPBlock != pBlock) {
			NotificationChain msgs = null;
			if (pBlock != null)
				msgs = ((InternalEObject)pBlock).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DelphiPackage.LIBRARY__PBLOCK, null, msgs);
			if (newPBlock != null)
				msgs = ((InternalEObject)newPBlock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DelphiPackage.LIBRARY__PBLOCK, null, msgs);
			msgs = basicSetPBlock(newPBlock, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, DelphiPackage.LIBRARY__PBLOCK, newPBlock, newPBlock));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
		switch (featureID) {
			case DelphiPackage.LIBRARY__PBLOCK:
				return basicSetPBlock(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
		switch (featureID) {
			case DelphiPackage.LIBRARY__PBLOCK:
				return getPBlock();
		}
		return super.eGet(featureID, resolve, coreType);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eSet(int featureID, Object newValue)
  {
		switch (featureID) {
			case DelphiPackage.LIBRARY__PBLOCK:
				setPBlock((programBlock)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eUnset(int featureID)
  {
		switch (featureID) {
			case DelphiPackage.LIBRARY__PBLOCK:
				setPBlock((programBlock)null);
				return;
		}
		super.eUnset(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public boolean eIsSet(int featureID)
  {
		switch (featureID) {
			case DelphiPackage.LIBRARY__PBLOCK:
				return pBlock != null;
		}
		return super.eIsSet(featureID);
	}

} //libraryImpl
