/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.delphi.delphi.DelphiPackage;
import org.xtext.example.delphi.delphi.objFieldList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>obj Field List</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class objFieldListImpl extends MinimalEObjectImpl.Container implements objFieldList
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected objFieldListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DelphiPackage.Literals.OBJ_FIELD_LIST;
  }

} //objFieldListImpl
