/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.delphi.delphi.DelphiPackage;
import org.xtext.example.delphi.delphi.recordConstant;
import org.xtext.example.delphi.delphi.recordFieldConstant;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>record Constant</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.delphi.delphi.impl.recordConstantImpl#getRecordField <em>Record Field</em>}</li>
 * </ul>
 *
 * @generated
 */
public class recordConstantImpl extends MinimalEObjectImpl.Container implements recordConstant
{
  /**
   * The cached value of the '{@link #getRecordField() <em>Record Field</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecordField()
   * @generated
   * @ordered
   */
  protected EList<recordFieldConstant> recordField;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected recordConstantImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DelphiPackage.Literals.RECORD_CONSTANT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<recordFieldConstant> getRecordField()
  {
    if (recordField == null)
    {
      recordField = new EObjectContainmentEList<recordFieldConstant>(recordFieldConstant.class, this, DelphiPackage.RECORD_CONSTANT__RECORD_FIELD);
    }
    return recordField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DelphiPackage.RECORD_CONSTANT__RECORD_FIELD:
        return ((InternalEList<?>)getRecordField()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DelphiPackage.RECORD_CONSTANT__RECORD_FIELD:
        return getRecordField();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DelphiPackage.RECORD_CONSTANT__RECORD_FIELD:
        getRecordField().clear();
        getRecordField().addAll((Collection<? extends recordFieldConstant>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DelphiPackage.RECORD_CONSTANT__RECORD_FIELD:
        getRecordField().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DelphiPackage.RECORD_CONSTANT__RECORD_FIELD:
        return recordField != null && !recordField.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //recordConstantImpl
