/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.delphi.delphi.DelphiPackage;
import org.xtext.example.delphi.delphi.structStmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>struct Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class structStmtImpl extends unlabelledStatementImpl implements structStmt
{
  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected structStmtImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return DelphiPackage.Literals.STRUCT_STMT;
	}

} //structStmtImpl
