/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.delphi.delphi.DelphiPackage;
import org.xtext.example.delphi.delphi.unlabelledStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>unlabelled Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class unlabelledStatementImpl extends CSTraceImpl implements unlabelledStatement
{
  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected unlabelledStatementImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return DelphiPackage.Literals.UNLABELLED_STATEMENT;
	}

} //unlabelledStatementImpl
