/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.delphi.delphi.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.delphi.delphi.DelphiPackage;
import org.xtext.example.delphi.delphi.variantType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>variant Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class variantTypeImpl extends typeImpl implements variantType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected variantTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DelphiPackage.Literals.VARIANT_TYPE;
  }

} //variantTypeImpl
