/*
 * generated by Xtext
 */
package uk.ac.yor.cs.asbh;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ASBHLangUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return uk.ac.yor.cs.asbh.ui.internal.ASBHLangActivator.getInstance().getInjector("uk.ac.yor.cs.asbh.ASBHLang");
	}
	
}
