/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package uk.ac.york.cs.miniocl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.york.cs.miniocl.parser.antlr.internal.InternalMiniOCLParser;
import uk.ac.york.cs.miniocl.services.MiniOCLGrammarAccess;

public class MiniOCLParser extends AbstractAntlrParser {

	@Inject
	private MiniOCLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMiniOCLParser createParser(XtextTokenStream stream) {
		return new InternalMiniOCLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RootCS";
	}

	public MiniOCLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MiniOCLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
