/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package uk.ac.york.cs.miniocl.miniOCL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.york.cs.miniocl.miniOCL.MiniOCLPackage
 * @generated
 */
public interface MiniOCLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MiniOCLFactory eINSTANCE = uk.ac.york.cs.miniocl.miniOCL.impl.MiniOCLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Root CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Root CS</em>'.
   * @generated
   */
  RootCS createRootCS();

  /**
   * Returns a new object of class '<em>Package CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Package CS</em>'.
   * @generated
   */
  PackageCS createPackageCS();

  /**
   * Returns a new object of class '<em>Class CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class CS</em>'.
   * @generated
   */
  ClassCS createClassCS();

  /**
   * Returns a new object of class '<em>Property CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property CS</em>'.
   * @generated
   */
  PropertyCS createPropertyCS();

  /**
   * Returns a new object of class '<em>Operation CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation CS</em>'.
   * @generated
   */
  OperationCS createOperationCS();

  /**
   * Returns a new object of class '<em>Parameter CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter CS</em>'.
   * @generated
   */
  ParameterCS createParameterCS();

  /**
   * Returns a new object of class '<em>Constraint CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint CS</em>'.
   * @generated
   */
  ConstraintCS createConstraintCS();

  /**
   * Returns a new object of class '<em>Invariant CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invariant CS</em>'.
   * @generated
   */
  InvariantCS createInvariantCS();

  /**
   * Returns a new object of class '<em>Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exp CS</em>'.
   * @generated
   */
  ExpCS createExpCS();

  /**
   * Returns a new object of class '<em>Logic Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logic Exp CS</em>'.
   * @generated
   */
  LogicExpCS createLogicExpCS();

  /**
   * Returns a new object of class '<em>Call Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Call Exp CS</em>'.
   * @generated
   */
  CallExpCS createCallExpCS();

  /**
   * Returns a new object of class '<em>Primary Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primary Exp CS</em>'.
   * @generated
   */
  PrimaryExpCS createPrimaryExpCS();

  /**
   * Returns a new object of class '<em>Name Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Name Exp CS</em>'.
   * @generated
   */
  NameExpCS createNameExpCS();

  /**
   * Returns a new object of class '<em>Rounded Bracket Clause CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rounded Bracket Clause CS</em>'.
   * @generated
   */
  RoundedBracketClauseCS createRoundedBracketClauseCS();

  /**
   * Returns a new object of class '<em>Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Literal Exp CS</em>'.
   * @generated
   */
  LiteralExpCS createLiteralExpCS();

  /**
   * Returns a new object of class '<em>Int Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Literal Exp CS</em>'.
   * @generated
   */
  IntLiteralExpCS createIntLiteralExpCS();

  /**
   * Returns a new object of class '<em>String Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Literal Exp CS</em>'.
   * @generated
   */
  StringLiteralExpCS createStringLiteralExpCS();

  /**
   * Returns a new object of class '<em>Boolean Literal Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Literal Exp CS</em>'.
   * @generated
   */
  BooleanLiteralExpCS createBooleanLiteralExpCS();

  /**
   * Returns a new object of class '<em>Path Name CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Path Name CS</em>'.
   * @generated
   */
  PathNameCS createPathNameCS();

  /**
   * Returns a new object of class '<em>Path Element CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Path Element CS</em>'.
   * @generated
   */
  PathElementCS createPathElementCS();

  /**
   * Returns a new object of class '<em>Boolean Exp CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Exp CS</em>'.
   * @generated
   */
  BooleanExpCS createBooleanExpCS();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MiniOCLPackage getMiniOCLPackage();

} //MiniOCLFactory
