/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package uk.ac.york.cs.miniocl.miniOCL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.york.cs.miniocl.miniOCL.MiniOCLPackage#getPrimaryExpCS()
 * @model
 * @generated
 */
public interface PrimaryExpCS extends CallExpCS
{
} // PrimaryExpCS
