<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="env" nsURI="http://uk.ac.york.cs.asbh.lang.cs2as/env/1.0" nsPrefix="env">
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedElements" upperBound="-1"
        eType="ecore:EClass TargetMM1.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentEnv" eType="#//Environment"/>
  </eClassifiers>
</ecore:EPackage>
