/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.plsql.dDL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.plsql.dDL.Comment#getTabname <em>Tabname</em>}</li>
 *   <li>{@link org.xtext.example.plsql.dDL.Comment#getColumnId <em>Column Id</em>}</li>
 *   <li>{@link org.xtext.example.plsql.dDL.Comment#getColname <em>Colname</em>}</li>
 *   <li>{@link org.xtext.example.plsql.dDL.Comment#getString <em>String</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.plsql.dDL.DDLPackage#getComment()
 * @model
 * @generated
 */
public interface Comment extends Definition
{
  /**
   * Returns the value of the '<em><b>Tabname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tabname</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tabname</em>' containment reference.
   * @see #setTabname(Tabname)
   * @see org.xtext.example.plsql.dDL.DDLPackage#getComment_Tabname()
   * @model containment="true"
   * @generated
   */
  Tabname getTabname();

  /**
   * Sets the value of the '{@link org.xtext.example.plsql.dDL.Comment#getTabname <em>Tabname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tabname</em>' containment reference.
   * @see #getTabname()
   * @generated
   */
  void setTabname(Tabname value);

  /**
   * Returns the value of the '<em><b>Column Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Column Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column Id</em>' attribute.
   * @see #setColumnId(String)
   * @see org.xtext.example.plsql.dDL.DDLPackage#getComment_ColumnId()
   * @model
   * @generated
   */
  String getColumnId();

  /**
   * Sets the value of the '{@link org.xtext.example.plsql.dDL.Comment#getColumnId <em>Column Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column Id</em>' attribute.
   * @see #getColumnId()
   * @generated
   */
  void setColumnId(String value);

  /**
   * Returns the value of the '<em><b>Colname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Colname</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colname</em>' containment reference.
   * @see #setColname(Colname)
   * @see org.xtext.example.plsql.dDL.DDLPackage#getComment_Colname()
   * @model containment="true"
   * @generated
   */
  Colname getColname();

  /**
   * Sets the value of the '{@link org.xtext.example.plsql.dDL.Comment#getColname <em>Colname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Colname</em>' containment reference.
   * @see #getColname()
   * @generated
   */
  void setColname(Colname value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see org.xtext.example.plsql.dDL.DDLPackage#getComment_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link org.xtext.example.plsql.dDL.Comment#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

} // Comment
