/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.plsql.dDL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create sequence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.plsql.dDL.Create_sequence#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.plsql.dDL.Create_sequence#getSequence_options <em>Sequence options</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.plsql.dDL.DDLPackage#getCreate_sequence()
 * @model
 * @generated
 */
public interface Create_sequence extends Definition
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.example.plsql.dDL.DDLPackage#getCreate_sequence_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.example.plsql.dDL.Create_sequence#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Sequence options</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.plsql.dDL.Sequence_options}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sequence options</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sequence options</em>' containment reference list.
   * @see org.xtext.example.plsql.dDL.DDLPackage#getCreate_sequence_Sequence_options()
   * @model containment="true"
   * @generated
   */
  EList<Sequence_options> getSequence_options();

} // Create_sequence
