/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.plsql.dDL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unique key</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.plsql.dDL.DDLPackage#getUnique_key()
 * @model
 * @generated
 */
public interface Unique_key extends Key
{
} // Unique_key
