/*
 * generated by Xtext
 */
package uk.ac.yor.cs.asbh.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.yor.cs.asbh.services.ASBHLangGrammarAccess;

public class ASBHLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ASBHLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected uk.ac.yor.cs.asbh.parser.antlr.internal.InternalASBHLangParser createParser(XtextTokenStream stream) {
		return new uk.ac.yor.cs.asbh.parser.antlr.internal.InternalASBHLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}
	
	public ASBHLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ASBHLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
