/*
* generated by Xtext
*/
package uk.ac.yor.cs.asbh.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ASBHLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("uk/ac/yor/cs/asbh/parser/antlr/internal/InternalASBHLang.tokens");
	}
}
