<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cCS2cAS" nsURI="http://classesCs2classesAS" nsPrefix="cCS2cAS">
  <eClassifiers xsi:type="ecore:EClass" name="RootCS2RootAS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootCS" eType="ecore:EClass ClassesCS.ecore#//RootCS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootAS" eType="ecore:EClass Classes.ecore#//Root"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassCS2ClassAS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classCS" eType="ecore:EClass ClassesCS.ecore#//ClassCS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classAS" eType="ecore:EClass Classes.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageCS2PackageAS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageCS" eType="ecore:EClass ClassesCS.ecore#//PackageCS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageAS" eType="ecore:EClass Classes.ecore#//Package"/>
  </eClassifiers>
</ecore:EPackage>
