/*
 * generated by Xtext
 */
package uk.ac.yor.cs.asbh.ui.contentassist

import uk.ac.yor.cs.asbh.ui.contentassist.AbstractASBHLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ASBHLangProposalProvider extends AbstractASBHLangProposalProvider {
}
